### ISSUE TITLE
TCP/IP communication over two different systems

### ISSUE THREAD

**Issue by ChiragVaghela10** [sourcedexter/SourceCodes#1]
We're trying to use your source code to transfer data, stored in simple txt file in system 1(server in our case) to system 2(client). But saying 'connection online' and then 'error establishing connection'. Hack!
It is working fine when I run client and server at same system. I am actually newbie in networking. Can you help us?

**Comment by sourcedexter** [comment]
I think the error might be occurring due to some ip address conflict. I think it is because the socket is not being created. 
well, I  afraid i cant help you much without more detils son the error.

**Comment by sourcedexter** [comment]
are you giving the right ip address of the server while running the client ? , else it might give the error you are facing.

**Comment by ChiragVaghela10** [comment]
Hi, I figured out I had some problems in connection settings but now it is working fine and you can now close the issue as well. Actually I had to implement RSA cryptography algorithm in real time using client-server architecture. The functionality of your server program is also expanded by my colleague working on same project. You might love to check it out :https://github.com/ChiragVaghela10/CryptographywithTCP-IP

**Comment by sourcedexter** [comment]
Oh cool, I will check it out
